Setting url
anypay/merchant-app pull request #46
Opened 2023-12-29 17:59 UTC by TalentedSunday

Added ability to change backend url on the setting page https://ibb.co/N2WRnx1

2024-02-01 23:56 UTC, pshenmic requested changes

2024-02-01 23:56 UTC, pshenmic commented on android/app/build.gradle
> +//            signingConfig signingConfigs.release
That should not be changed, probably accidentally pushed

2024-02-01 23:56 UTC, pshenmic commented on lib/client.dart
> +  static String domain = 'anypay.pshenmic.dev';
Don't change default API

2024-02-01 23:56 UTC, pshenmic commented on lib/client.dart
> +    if (str != null && str.length > 0) return StringUtils.capitalize(str);
Revert all formatting

2024-02-01 23:56 UTC, pshenmic commented on lib/generated_plugin_registrant.dart
> +// Generated file. Do not edit.
It says generated file, should it be pushed? What is it used for?

2024-02-01 23:56 UTC, pshenmic commented on lib/package_info_helper.dart
> +import 'package:package_info_plus/package_info_plus.dart';
I think that file relates to the different PR, isn't it?

2024-02-01 23:56 UTC, pshenmic commented on lib/routes/settings.dart
> +  // Widget _buildAboutUs(context) {
Remove out commented code

2024-02-01 23:56 UTC, pshenmic commented on pubspec.yaml
> +version: 2.3.1+19
Don't change the version, it will be done before merging to staging branch

2024-02-06 19:54 UTC, closed without merging

2024-02-09 17:19 UTC, TalentedSunday commented on pubspec.yaml
> +version: 2.3.1+19
This is 19 in the master branch, I think part of the issue we are having is that I pulled from master and you are asking me to push to develop and there are differences between develop and master