2nd commit
anypay/merchant-app pull request #47
Opened 2024-02-07 15:40 UTC by TalentedSunday

build.gradle file restored
client.dart: url and indentation restored
genrated_plugin_file removed
package_info removed from this branch
setting_dart commented code removed
version restored

2024-02-07 16:17 UTC, pshenmic requested changes
Clean it up, make a proper PR title, and beautify PR description

2024-02-07 16:17 UTC, pshenmic commented on .fvm/fvm_config.json
You don't need to commit that

2024-02-07 16:17 UTC, pshenmic commented on android/app/build.gradle
> +    java {
What is it?

2024-02-07 16:17 UTC, pshenmic commented on assets/fonts/Ubuntu-Bold.ttf
Why you comitted empty files?

2024-02-07 16:17 UTC, pshenmic commented on assets/images/anypay-full-logo.png
What's changed here?

2024-02-07 16:17 UTC, pshenmic commented on lib/client.dart
> +    var response = await makeRequest(
Revert formatting

2024-02-07 16:17 UTC, pshenmic commented on lib/main.dart
> +  setDefaultUrl();
Isn't that should happen before authentication?

2024-02-07 16:17 UTC, pshenmic commented on push_to_docker.sh
What is it empty file for?

2024-02-07 16:17 UTC, pshenmic commented on pubspec.yaml
> +  package_info_plus: ^3.1.2
That is not used in this PR

2024-02-08 19:57 UTC, TalentedSunday commented on lib/client.dart
> +    var response = await makeRequest(
I cannot change those variables types . If I make those variables final from String, functionality won't work in which base url is being updated

2024-02-08 20:08 UTC, TalentedSunday commented on lib/main.dart
> +  setDefaultUrl();
This checks If the user has changed the url and there is a new url stored in the local data, then instead of the deleted url, it loads the url from the locally stored url, which was stored by the user when he changed the base url in the settings screen. By removing the code, it will not store the url locally; every time the user restarts the app, the url will be changed.

2024-02-08 20:22 UTC, pshenmic commented on lib/client.dart
> +    var response = await makeRequest(
I meant revert all the formatting in your PR that does not change any code

2024-02-08 20:27 UTC, pshenmic commented on lib/main.dart
> +  setDefaultUrl();
Should it happen before or after authentication?

2024-02-09 17:03 UTC, EmmanuelEklipse commented on assets/fonts/Ubuntu-Bold.ttf
It's there in the original file, I did not add it.

2024-02-09 17:03 UTC, TalentedSunday commented on assets/images/anypay-full-logo.png
Nothing, same as before

2024-02-09 17:03 UTC, TalentedSunday commented on assets/fonts/Ubuntu-Bold.ttf
I did nto add it, it's in the code that I pulled from master

2024-02-09 17:03 UTC, TalentedSunday commented on assets/images/anypay-full-logo.png
Nothing, same as always

2024-02-09 17:05 UTC, TalentedSunday commented on push_to_docker.sh
Don't know, it's like that in the master repo

2024-02-09 17:29 UTC, TalentedSunday commented on assets/fonts/Ubuntu-Bold.ttf
For example, here is what I mean

![image](https://github.com/anypay/merchant-app/assets/49331376/057fc579-6dc4-42d7-87f8-d77aefd70c3f)

2024-02-11 20:58 UTC, pshenmic commented on assets/fonts/Ubuntu-Bold.ttf
Revert this change, it shouldn't be shown in the git diff as change

2024-02-11 21:01 UTC, pshenmic commented on assets/images/anypay-full-logo.png
<img width="1168" alt="image" src="https://github.com/anypay/merchant-app/assets/17009187/f90bae1d-3753-4444-9ef1-9df2ecfa435b">

Size of the image was changed

2024-02-11 21:05 UTC, pshenmic commented on push_to_docker.sh
We are merging into develop

2024-02-16 17:38 UTC, closed without merging