Task : Add ability to change backend URL on the setting page #52
anypay/merchant-app pull request #54
Opened 2024-02-21 20:22 UTC by Emmanueleclipse

### Things done

- Added the ability to change the backend URL on the settings page
- Added a pop-up confirmation form
- Set a different color for the "Save" button in light mode and dark mode
- Made URL scrollable 
![image](https://github.com/anypay/merchant-app/assets/49331376/732b3669-4cd0-41b7-8bc8-6114082e16dc)
![image](https://github.com/anypay/merchant-app/assets/49331376/3a38a313-6814-4fdf-9f28-7a1b9f8b687a)
![image](https://github.com/anypay/merchant-app/assets/49331376/2811f3fe-7abd-4b86-bdc1-2dba85983f0a)

2024-02-24 19:01 UTC, pshenmic requested changes

2024-02-24 19:01 UTC, pshenmic commented on lib/main.dart
> +  setDefaultUrl();
Is not it should happen before checking for authentication? What is the reasons to place it after?

2024-02-24 19:01 UTC, pshenmic commented on lib/main.dart
> +    Client.protocol = url.scheme;
I think we could add a new method in the Client class that will allow you to change the url instead of changing it directly outside of the class

2024-02-24 19:01 UTC, pshenmic commented on lib/main.dart
> +    Client.domain = storedUrl.replaceAll("${url.scheme}://", "");
Even better, we can use Uri instead of protocol, domain and host in the Client class so that this line would not be needed

2024-02-24 19:01 UTC, pshenmic commented on lib/routes/edt_url.dart
edit_backend_url.dart

2024-02-24 19:01 UTC, pshenmic commented on lib/routes/edt_url.dart
> +class EditUrl extends StatelessWidget {
EditBackendUrl

2024-02-24 19:01 UTC, pshenmic commented on lib/routes/edt_url.dart
> +    return EditUrlPage(title: "Edit Url");
Edit Backend URL

2024-02-24 19:01 UTC, pshenmic commented on lib/router.dart
> +      'settings/edit_url',
settings/backend_url

2024-02-24 19:01 UTC, pshenmic commented on lib/main.dart
> +  final storedUrl = await FlutterSecureStorage(
We already have a Storage class, I feel like we should use that

2024-02-24 19:01 UTC, pshenmic commented on lib/routes/edt_url.dart
> +                          if (isUserLoggedIn == true) {
You don't need to check whether user is logged in, simply logout every time

2024-02-24 19:01 UTC, pshenmic commented on lib/routes/edt_url.dart
> +  void _rebuild() {
I think that's left from copy paste

2024-02-24 19:01 UTC, pshenmic commented on lib/routes/edt_url.dart
> +  var urlController = TextEditingController();
Make some line breaks to make it look pretty

2024-02-24 19:01 UTC, pshenmic commented on lib/routes/edt_url.dart
> +                      return "Please provide valid url";
I think you can invert condition and avoid code duplication. Check for value is not null and isAbsolute

2024-02-24 21:07 UTC, Emmanueleclipse commented on lib/main.dart
> +  setDefaultUrl();
It doesn't really matter because when it's checking for authentication, it doesn't use URI. but, I changed it.

2024-02-24 21:10 UTC, Emmanueleclipse commented on lib/routes/edt_url.dart
> +                          if (isUserLoggedIn == true) {
It's not good practice to call a method when it's not required. Here, this logic has been setup for a user changing URL from the login screen and since a user wont be logged in when they navigate from the login screen, then there is no point in calling the logout function.

2024-02-24 21:32 UTC, pshenmic requested changes

2024-02-24 21:32 UTC, pshenmic commented on lib/routes/edit_backend_url.dart
> +                          setState(() {
I think we don't need setState to modify Client backend url

2024-02-24 21:32 UTC, pshenmic commented on lib/routes/edit_backend_url.dart
> +                          if (isUserLoggedIn == true) {
Let's remove user logged in check here and just use logout every time

2024-02-24 21:32 UTC, pshenmic commented on lib/routes/edit_backend_url.dart
> +    setState(() {
Is it still used?

2024-02-24 21:32 UTC, pshenmic commented on lib/routes/edit_backend_url.dart
> +          style: TextStyle(
I have been defining global styles for TextStyle, so probably that one is not necessary

2024-02-24 21:56 UTC, Emmanueleclipse commented on lib/routes/edit_backend_url.dart
> +          style: TextStyle(
We require it only for the title, because the text color remains the same (Black) even in dark mode.

2024-02-24 22:40 UTC, pshenmic commented on lib/routes/edit_backend_url.dart
> +          style: TextStyle(
Use dialogTheme in the ThemeData

2024-02-24 22:41 UTC, pshenmic requested changes

2024-02-24 22:41 UTC, pshenmic commented on lib/routes/settings.dart
> +                  child: Text("Edit backend URL",
Backend URL

2024-02-24 22:41 UTC, pshenmic commented on lib/routes/edit_backend_url.dart
> +                  labelText: 'Update Backend Url',
Backend URL

2024-02-24 22:43 UTC, pshenmic requested changes

2024-02-24 22:43 UTC, pshenmic commented on lib/routes/edit_backend_url.dart
> +  var _successMessage = '';
Remove unused fields from the page

2024-02-24 22:43 UTC, pshenmic commented on lib/main.dart
> +        elevatedButtonTheme: ElevatedButtonThemeData(
This is not used anymore

2024-02-25 14:54 UTC, pshenmic requested changes

2024-02-25 14:54 UTC, pshenmic commented on lib/routes/settings.dart
> +  var urlController = TextEditingController();
I think we forgot to remove this from the settings, it is not used anymore here

2024-02-25 15:03 UTC, pshenmic requested changes

2024-02-25 15:03 UTC, pshenmic commented on lib/routes/settings.dart
> +                    _EditUrlLink(),
Missing context

2024-02-25 15:30 UTC, pshenmic approved these changes
Good job 👍

2024-02-25 18:49 UTC, merged